### ISSUE TITLE
No longer working on android

### ISSUE THREAD

**Issue by ahtokca** [includable/react-native-email-link#107]
When I use openInbox then I see in the logcat

```
 AppsFilter: interaction: PackageSetting{62a2d58 app.package/10165} -> PackageSetting{5566446 com.google.android.gm/10132} BLOCKED
```

Looks like it is broken by recent security changes on android

**Comment by tschoffelen** [comment]
Please ensure to follow the instructions in the README to whitelist your application for opening email apps.

**Comment by ahtokca** [comment]
@tschoffelen thanks for the rapid answer. but please don't jump to conclusions. The package stopped working out of the blue. I checked https://github.com/includable/react-native-email-link#readme and found nothing about any whitlist. Could you please help me sort it out?

**Comment by ahtokca** [comment]
> Please ensure to follow the instructions in the README to whitelist your application for opening email apps.

Well it requires QUERY_ALL_PACKAGES permission on android 30+ which is big thing to get approved nowadays.

**Comment by tschoffelen** [comment]
That is weird, the query as is used to work fine on Android 11 and 12.

You wouldn't want to switch to query_all_packages permission though, rather you'd specify each of the individual packages (email clients) you wish to support. We do something similar for iOS:
https://github.com/includable/react-native-email-link/blob/master/README.md?plain=1#L48

**Comment by tschoffelen** [comment]
And apologies for being a bit too over-eager in closing this issue!

**Comment by ahtokca** [comment]
@tschoffelen figured out. That's some how stale version in node_modules/ without queries in manifest
so `npm ci` helped
works now
