### ISSUE TITLE
Even I installed the some email apps those are not showing in intent modal

### ISSUE THREAD

**Issue by maheshmuttinti** [includable/react-native-email-link#109]
## Android 

I've used the `openInbox()` method.

In IOS all apps are showing in the intent modal. but in android few apps like outlook, yahoo mail apps are not showing in the intent modal.

So, please fix this issue.

In the Below table, I've mentioned the table which you can check.

| email client | device type | status |
| ------ | ------ |  ---- |
| Apple Mail | Android | Won't work on Android |
| Gmail | Android | Installed and Opened the app |
| ProtonMail | Android | Installed and Opened the app |
| Fastmail | Android | Installed and Opened the app |
| Inbox | Android | Installed and Not Opened the app |
| Spark | Android | Installed and Not Opened the app |
| Airmail | Android | Installed and Not Opened the app |
| Outlook | Android | Installed and Not Opened the app |
| Yahoo Mail | Android | Installed and Not Opened the app |
| Superhuman | Android | Not available in Playstore |
| Yandex | Android | Installed and Not Opened the app |

**Comment by Daidalos117** [comment]
Could this be due the new "feature" of android OS which limits [chooser for 2-3 items](https://issuetracker.google.com/issues/134367295)? 
I didn't find any issue mentioning this here, but it's exactly what happening for me. I have 5 clients installed in the phone, but only 3 gets shown, and no way to influence this list.
