### ISSUE TITLE
Apple Mail vs Default email reader

### ISSUE THREAD

**Issue by nicolasdevienne** [includable/react-native-email-link#110]
Apple Mail is renamed with "Default email reader" with last version 1.14.1

previous version installed (1.13.1), we have "Mail"
![IMG_8534](https://user-images.githubusercontent.com/65358122/181777672-b6b7a011-b56b-407d-b34e-2e4798cadbf8.PNG)

last version installed (1.14.1), we have "Default email reader"
![IMG_8535](https://user-images.githubusercontent.com/65358122/181777797-ec76e3e2-0b2c-4c65-94b7-4802c813c579.PNG)

**Comment by nicolasdevienne** [comment]
Hi @tschoffelen ! No PR for this issue ? :)

**Comment by tschoffelen** [comment]
What solution would you suggest for this?

This change was made because now iOS has the option to change the default mail client, this first option didn't always link to the stock 'Mail' app anymore (since we're using the `mailto://` URL scheme).

See the discussion in this PR here: https://github.com/includable/react-native-email-link/pull/108

**Comment by nicolasdevienne** [comment]
I don't understand how it works ? I have 3 mail clients installed on my iPhone : Apple Mail, Outlook and Gmail. If Apple Mail is my default mail client, I have 3 options in action sheet as you can see on my screenshort and the first option open Apple Mail. If Outlook is my default mail client, I have the same option but "Outlook" option is not replace by "Mail" option... I have 2 options for the same client mail and no option for Apple Mail... Yet I have this configuration in my Info.plist :

```
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>message</string>
		<string>readdle-spark</string>
		<string>airmail</string>
		<string>ms-outlook</string>
		<string>googlegmail</string>
		<string>inbox-gmail</string>
		<string>ymail</string>
		<string>superhuman</string>
		<string>yandexmail</string>
		<string>fastmail</string>
		<string>protonmail</string>
	</array>
```

Maybe I forget something ?...

**Comment by tschoffelen** [comment]
Apple doesn't give us the ability to detect what email client is set as the default one unfortunately, this is just the app that the system tells to respond to the `mailto://` URI scheme.

There is also no URI scheme that specifically targets Apple Mail, so if you have another client set to default, we can't open the Apple Mail app to draft a message. These are just iOS limitations, nothing I can see that we could so differently in this library to be more user friendly unfortunately...

**Comment by nicolasdevienne** [comment]
Hi @tschoffelen and thank you! Is it possible to translate "Default email reader" for French app?

**Comment by nicolasdevienne** [comment]
@tschoffelen

**Comment by nicolasdevienne** [comment]
@tschoffelen I can't push my PR

```
remote: Permission to includable/react-native-email-link.git denied to nicolasdevienne.
fatal: unable to access 'https://github.com/includable/react-native-email-link.git/': The requested URL returned error: 403

```
Can you give me permission ?

**Comment by tschoffelen** [comment]
You can't push directly to this repository - you'd push to your own fork, then create a PR.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by nicolasdevienne** [comment]
@tschoffelen done! https://github.com/includable/react-native-email-link/pull/113
