### ISSUE TITLE
Influence list of email clients on iOS

### ISSUE THREAD

**Issue by Daidalos117** [includable/react-native-email-link#111]
Hello,
I noticed that the list of email clients is hardcoded in the code of the library. But we want to add some email clients used in our country.
I could make a PR with changes necessary for rewriting the list, I was thinking something easy like:

```
let prefixes = {
  "apple-mail": "message://",
  gmail: "googlegmail://",
  ...
}

const setPrefixes = (newPrefixes: typeof prefixes) => prefixes = newPrefixes;
```
Same for titles and uriParams vars.
and then on our side just
```
setPrefixes({custom: 'szn-email://'})
...
openInbox();
```
Would this be suitable for you, or do you prefer us making our own fork and implementing that there?
Thank you in advance!

**Comment by tschoffelen** [comment]
Good idea! We could also add this as an option to the `openInbox` method:

```js
openInbox({
   title: 'What email app do you want to open?',
   additionalPrefixes: {
       ...
   }
});
```

Or, also always happy of course to add new email apps as default options to the library! The more the merrier!

**Comment by Daidalos117** [comment]
Sounds good! What would you prefer? Possibility to add additional data or just adding new ones to library? Honestly I don't have an opinion on this 😅

**Comment by tschoffelen** [comment]
Adding new ones to the library would be best I think, has direct added value for other users of the lib

**Comment by Daidalos117** [comment]
Good point :) I have created a PR. But I wanted to ask, how do you got to know what path is app using for opening a mail? Did you contact the authors of the email clients?

**Comment by tschoffelen** [comment]
Just a lot of googling and experimenting for most of them...
