### ISSUE TITLE
Unable to run on 0.68.2 RN

### ISSUE THREAD

**Issue by NazmaD** [includable/react-native-email-link#115]
![image](https://user-images.githubusercontent.com/15101564/210716188-032fb1a1-803c-4399-bc27-29e2fd709b85.png)

Facing issue after upgrading RN Version to 0.68.2. can someone help
FYI, I am on react-native-email-link:1.14.3

**Comment by tschoffelen** [comment]
Interesting! Would you mind sharing your code that shows how you call the library?

**Comment by NazmaD** [comment]
import {openComposer} from 'react-native-email-link'; 

  onEmailClick() {
    const {user} = this.props;
    openComposer({to: user.email});
  }
  
This is the usage

FYI
dependencies: {
    "react": "17.0.2",
    "react-native-email-link":"1.14.3",
    "react-native": "0.68.2",
    },
  "devDependencies": {
    "@babel/preset-env": "^7.20.2",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/enzyme": "3.10.4",
    "@types/enzyme-adapter-react-16": "^1.0.5",
    "@types/jest": "^24.0.24",
    "@types/jsdom": "^12.2.4",
    "@types/node": "^12.12.21",
    "@types/react": "^16.9.16",
    "@types/react-native": "^0.60.25",
    "@types/react-native-calendars": "^1.20.7",
    "@types/react-native-vector-icons": "^6.4.5",
    "@types/react-redux": "^7.1.5",
    "@types/react-test-renderer": "^16.9.1",
    "@types/redux-logger": "^3.0.7",
    "@types/uuid": "^3.4.6",
    "@typescript-eslint/eslint-plugin": "^2.12.0",
    "appium": "^1.22.3",
    "appium-doctor": "^1.16.2",
    "babel-jest": "^26.6.3",
    "babel-plugin-ignite-ignore-reactotron": "^0.3.0",
    "babel-plugin-module-resolver": "^3.1.1",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "enzyme-to-json": "^3.4.3",
    "eslint": "^7.32.0",
    "eslint-config-airbnb-typescript": "^6.3.1",
    "eslint-config-prettier": "^6.7.0",
    "eslint-plugin-import": "^2.19.1",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-prettier": "^3.1.2",
    "eslint-plugin-react": "^7.17.0",
    "eslint-plugin-sonarjs": "^0.5.0",
    "husky": "^4.2.5",
    "ignite-standard": "1.0.0",
    "jest": "^26.6.3",
    "jest-junit": "^10.0.0",
    "jest-sonar-reporter": "^2.0.0",
    "jetifier": "^1.6.5",
    "jsdom": "^16.0.1",
    "jsdom-global": "^3.0.2",
    "metro-react-native-babel-preset": "^0.67.0",
    "mockery": "^2.1.0",
    "patch-package": "^6.2.0",
    "postinstall-postinstall": "^2.0.0",
    "prettier": "^1.19.1",
    "react-devtools-core": "3.6.0",
    "react-dom": "16.7.0",
    "react-test-renderer": "17.0.2",
    "reactotron-react-native": "^2.1.0",
    "reactotron-redux": "^2.1.0",
    "sonar-scanner": "^3.1.0",
    "ts-jest": "^24.2.0",
    "types": "^0.1.1",
    "typescript": "^4.0.3",
    "wd": "^1.12.0"
  },
