### ISSUE TITLE
Specifying subject in openComposer throws an error when selecting Default mail reader on iOS

### ISSUE THREAD

**Issue by karel-suchomel-ed** [includable/react-native-email-link#118]
As the title says I'm trying to compose an email using this library with subject and body, but when selecting the Default mail reader it throws an error:
`[Error: Unable to open URL: file:///private/var/containers/Bundle/Application/23727D6B-B7ED-4C2F-BE2E-85F06F2F9D77/Example.app/mailto:...%3Fsubject=Mobile%20application%20customer%20support. Add file to LSApplicationQueriesSchemes in your Info.plist.]`

When I select for example Gmail, it works correctly

If I remove the subject, it works even with the Default mail reader

This is how I'm calling the method
```
openComposer({
     body,
     subject,
     title: '',
     message: t('modals.email_app.dialog.text'),
     cancelLabel: t('buttons.cancel', {ns: 'general'}),
     to: `mailto:${url}`
   }).catch(() => {
     Alert.alert(t('modals.email_app.title'), t('modals.email_app.text'))
   })
```

I tried using the default Linking API with mailto:email@email.com?cc=$subject=${subject}&body=${body}and it is resulting in the same error

**Comment by animmore** [comment]
the same

**Comment by martinblampied** [comment]
Anyone find a work around?

**Comment by giacomoalonzi** [comment]
Same here! 0.71.3

**Comment by tschoffelen** [comment]
This sounds like it is a React Native bug if it doesn't work with the `Linking` module directly either.

Could someone open an issue in [facebook/react-native](https://github.com/facebook/react-native/issues) and reference this one?

**Comment by tschoffelen** [comment]
It looks like iOS might now to require adding the mailto scheme to LSApplicationQueriesSchemes. Adding it in your Info.plist should help.

**Comment by giacomoalonzi** [comment]
> It looks like iOS might now to require adding the mailto scheme to LSApplicationQueriesSchemes. Adding it in your Info.plist should help.

Thanks for the reply, in expo we need to do something in the configuration of the plugin?

**Comment by martinblampied** [comment]
I had mailto in my plist but still have the same issue. I also added file as per the error message but that didn't fix. 

Appears to be something with the subject/body. If I only populate the 'to' it works. If I add a subject or body it fails.

**Comment by giacomoalonzi** [comment]
Any update about this? I've installed the latest release of this lib but nothing has changed.

**Comment by giacomoalonzi** [comment]
> @tschoffelen I had mailto in my plist but still have the same issue. I also added file as per the error message but that didn't fix.
> 
> Appears to be something with the subject/body. If I only populate the 'to' it works. If I add a subject or body it fails.

I have the same problem even without the plugin, if I add a subject or body with Linking API the result is the same. 🤔

**Comment by AndreiBehel** [comment]
@martinblampied I can confirm if only 'to' is present it works. Otherwise the error is thrown

**Comment by AndreiBehel** [comment]
@karel-suchomel-ed @giacomoalonzi I've made small investigation. You can simply encode your subject and body using encodeURIComponent().

**Comment by martinblampied** [comment]
@AndreiBehel - sorry for late reply. That worked thanks 👍

**Comment by fansilva1991** [comment]
> @karel-suchomel-ed @giacomoalonzi @martinblampied I've made small investigation. Incorrect encoding is the root of this issue. So you can simply encode your subject and body using encodeURIComponent() if your platform is iOS.
> 
> `openComposer({ to: Emails.SUPPORT_EMAIL, subject: Platform.OS === 'ios' ? encodeURIComponent(yourSubject) : yourSubject, body: Platform.OS === 'ios' ? encodeURIComponent(yourBody) : yourBody, });`
> 
> Or you can use 'encodeBody: true' if you have problems with body

I had the same problem, and this also solved my issue. Thanks @AndreiBehel !

**Comment by fansilva1991** [comment]
> Should we build this into the library? I'm happy to accept a PR for this change.

Hi, @tschoffelen I opened a PR ( https://github.com/includable/react-native-email-link/pull/125 ) which adds support to encode the subject. 

I hope you guys can review it :)
