### ISSUE TITLE
[IOS] Recipient's email address is not filled for YandexMail and ProtonMail for openComposer

### ISSUE THREAD

**Issue by Navipro70** [includable/react-native-email-link#121]
1. Open app
2. Execute the next piece of code
```
await openComposer({
      cancelLabel: 'Cancel',
      message: 'What app do you want to open?',
      title: "",
      to: example@gmail.com,
});
```
3. Choose `ProtonMail` or `YandexMail` as mail app

Current behavior:
`ProtonMail` and `YandexMail` opens without filled field for recipient mail
| ProtonMail | YandexMail |
| --------------- | --------------- |
| <img src="https://user-images.githubusercontent.com/60893275/231138447-f50efbb0-89f0-4261-b2b3-d7b8f57a3c23.jpg" alt="ProtonMail without filled recipient" width="260" height="550"/> | <img src="https://user-images.githubusercontent.com/60893275/231138455-67fa7a7c-30ee-4f13-98cb-5596852b5b11.jpg" alt="YandexMail without filled recipient" width="260" height="550"/> | 

Expected behavior:
`ProtonMail` and `YandexMail` opens with filled field for recipient mail from `to` param
| ProtonMail | YandexMail |
| --------------- | --------------- |
| <img src="https://user-images.githubusercontent.com/60893275/231138485-e2fd29d5-617e-4054-baf2-ba71de7f0468.jpg" alt="ProtonMail with filled recipient" width="260" height="550"/> | <img src="https://user-images.githubusercontent.com/60893275/231138489-6f3dff62-699a-4eea-bfdf-f2c78463f850.jpg" alt="YandexMail with filled recipient" width="260" height="550"/> |

**Comment by tschoffelen** [comment]
I don't have any accounts on either of these services, so won't be able to help fix this myself, but of course would happily accept a PR that changes the URL structure used here.

**Comment by Navipro70** [comment]
Maybe you know where I can find correct params for this mails?

I've tried pass similar parameters in link as for web apps (Yandex only as I remember), but it haven't worked, I provide a link: https://mail.yandex.ru/compose?mailto=example@example.com&subject=Hello&body=Text

Also I didn't find any documentation or API for both of them,

**Comment by McFly78** [comment]
For ProtonMail
the URL is: 
URL="protonmail://mailto:foobar@foobar.org?subject=SubjectTitleOfEMail&body=MessageBodyFooBar"
https://github.com/ProtonMail/ios-mail/issues/27

A did a quick modification for openComposer() on IOS and it's working for me.
[ios.js.zip](https://github.com/includable/react-native-email-link/files/11542842/ios.js.zip)

**Comment by tschoffelen** [comment]
Thanks @McFly78! Any chance you would be able to open a PR to incorporate this into the repo?

**Comment by jnak** [comment]
@McFly78 +1 for sending a PR :) Seems like an easy fix
