### ISSUE TITLE
Open the apple-mail doesn't work 

### ISSUE THREAD

**Issue by Sahand-Stefan** [includable/react-native-email-link#122]
openComposer({
      app: "apple-mail",
      to: email,
      subject,
      body,
    })

In this code i am trying to open the apple main as maybe some users are not using gmail. The apple main is not opening the mail-box but gmail opens,
The second question is that how can i make it generic to open apple-main or gmail either of them?

**Comment by tschoffelen** [comment]
Hi @Sahand-Stefan, apologies for the late response.

I don't think `app` is a supported parameter. The library will show a sheet to prompt the user to select their preferred app if multiple supported apps are detected, if there's only one there's no prompt shown.
