### ISSUE TITLE
openComposer only opens up native mail app iOS

### ISSUE THREAD

**Issue by eikhunter** [includable/react-native-email-link#124]
Hi, I have followed the install instructions for the library, everything seems to be working as expected on Android, but iOS will only ever default open the native iOS "mail" app and not give any options for any other app installed. Using

`openComposer({
      to: email,
    });`

If I specify the param of `app` and give it a specific application to open it works as expected, but I want the options of all the app installed first.

Info.plist
```
<key>LSApplicationQueriesSchemes</key>
<array>
    <string>cydia</string>
    <string>undecimus</string>
    <string>sileo</string>
    <string>zbra</string>
    <string>whatsapp</string>
    <string>mailto</string>
    <string>message</string>
    <string>readdle-spark</string>
    <string>airmail</string>
    <string>ms-outlook</string>
    <string>googlegmail</string>
    <string>inbox-gmail</string>
    <string>ymail</string>
    <string>superhuman</string>
    <string>yandexmail</string>
    <string>fastmail</string>
    <string>protonmail</string>
    <string>szn-email</string>
</array>
```
Sorry if I have missed a crucial step in the installation, but I can't seem to figure out why it won't give the options.

Thanks in advance

**Comment by watadarkstar** [comment]
I'm having the same issue. What version are you on? I'm on:

```
    "react-native-email-link": "1.14.6",
```

**Comment by bharathkandula99** [comment]
Any luck?

**Comment by crackhack8266** [comment]
any luck ?

**Comment by sammiepls** [comment]
Experiencing this as well even on the current latest version 1.16.1
