### ISSUE TITLE
Expo setup docs clarification

### ISSUE THREAD

**Issue by frozencap** [includable/react-native-email-link#129]
Could someone explain what this means 

> Expo – Enable Config Plugin
> Want this library to work on Android too? Because the library uses native code on Android you need to [follow Expo's guide](https://docs.expo.dev/workflow/customizing/) for custom native code.

Does the config plugin not handle Android?

**Comment by tschoffelen** [comment]
The library includes native Java code to provide the functionality on Android, which isn't supported in Expo Go, unless you build the app yourself (development builds is what Expo calls this I think?).
