### ISSUE TITLE
"Default email reader" is not working on ios 

### ISSUE THREAD

**Issue by canerkaynar** [includable/react-native-email-link#134]
Hi!, when I tap the default email reader, Nothing happens. Even if I change the default email reader from settings. Do you have any opinion? 

System: iOS 16.6.1
Device: iPhone 11

**Comment by elyobo** [comment]
With the default Mail app uninstalled and Gmail installed I get "Default email reader" and "Gmail" options; given that the default mail app isn't available it doesn't seem like it should show up. Selecting it rejects the promise with an error and, separately, iOS offers to reinstall the app.
