### ISSUE TITLE
Not working 100%?

### ISSUE THREAD

**Issue by breadadams** [includable/react-native-email-link#3]
We're testing this on iOS and Android and seeing mixed results from the same code. We have a button, running `openInbox()` onPress.

* iOS (11)
  * **Simulator:** ~~Nothing occurs when running the method, although I have a feeling this could be due to not having any accounts setup on the device.~~ Expected behaviour.
  * **Real device:** ~~Always get taken directly to the system Mail.app, even though I have Gmail installed and configured~~ [**Resolved**](https://github.com/includable/react-native-email-link/issues/3#issuecomment-397818344)

* Android
  * **Simulator:** Nothing occurs when running the method, I have a configured gmail account on the device.
  * **Real device:** Nothing occurs when running the method, there are mail accounts configured on the device

We have added the `LSApplicationQueriesSchemes` keys as specified in README, are there any 
 other steps not documented?

**Comment by tschoffelen** [comment]
I must admit that I have not tested it with the Gmail app for iOS anytime recently - seems like the URL scheme might have changed.

This library does not currently support Android. I do have working code available for opening the inbox on Android, but haven’t yet found the time to merge it since it’s native code and will require a bit more testing then the simple Javascript required to make this work on iOS.

I understand you’re actively working on making this work for your app, so if I add the native code to a separate branch, could you try to merge it into the existing code in this lib? Would that work for you?

**Comment by tschoffelen** [comment]
Oh, and of course thanks for taking the time to look into this lib and for your PRs!

**Comment by breadadams** [comment]
My pleasure @tschoffelen, thanks for the handy lib 😄. In response to your comments:

> seems like the URL scheme might have changed.

True, that could be the case, I'll look into it.
___

> This library does not currently support Android

Darn, the `Platform.OS` conditionals in `index.js` got me thinking it was cross-platform.
___

> Would that work for you?

Absolutely, we can give that a go 👍

**Comment by tschoffelen** [comment]
Alright, I just created the branch [android-support](https://github.com/includable/react-native-email-link/tree/android-support). Did it quickly during lunch, so didn't actually have a change to test anything, but I added the native Android code, as well as the JS that should be able to invoke that native code. What I'm not sure about yet is if there's more that needs to be done for this to be properly compiled when you run `react-native link`.

**Comment by breadadams** [comment]
Lovely @tschoffelen, we'll take a look at it asap

cc: @gabrielperales - if you get a chance before me ☝️

**Comment by gabrielperales** [comment]
@tschoffelen I couldn't make it work for android. I'll try to fix it at some point, but for now, we are going to keep working on our app without this feature.

**Comment by breadadams** [comment]
iOS gmail is working if you follow #4 

![image](https://user-images.githubusercontent.com/5795227/41499824-7a85ab1c-7187-11e8-9320-45012254840c.png)

It'd be good if someone could test the other providers

**Comment by tschoffelen** [comment]
Great, thanks!

**Comment by mvanroon** [comment]
Android supports picking an email client out of the box. What I did in my (Android-specific) code was simply:
```
import { Linking } from 'react-native
Linking.openURL('mailto')
```

**Comment by tschoffelen** [comment]
@Mvanroon that will open the email _composer_ though, not the _inbox_, right?

Main purpose of this library (at least for my usage) is to open the inbox so that if you send a confirmation/magic link email of sorts, you can get the user to the right place. Example:

```
User enters email
-> magic link login email is sent
-> screen is shown that user should open magic link in email
-> user clicks button to view inbox
-> user clicks link in email
-> link redirects back to app and completes passwordless login
```

**Comment by mvanroon** [comment]
right that makes sense - sorry

Any progress on android support? Could this help? https://github.com/chirag04/react-native-mail/issues/59#issuecomment-347872652

**Comment by tschoffelen** [comment]
The native code in the [`android-support` branch](https://github.com/includable/react-native-email-link/tree/android-support) should work (I'm using it in production, but not as part of this library), but linking etc. still needs to be sorted out before that branch can be merged into master.

**Comment by mvanroon** [comment]
Cool. I made some adjustments: https://github.com/includable/react-native-email-link/pull/11

**Comment by tschoffelen** [comment]
Great, thanks @mvanroon! Can you confirm the PR I just merged fixes the Android problems?

**Comment by mvanroon** [comment]
Yep. Working fine in my apps. Feel free to try it out.

**Comment by tschoffelen** [comment]
Sorry, bit of a lazy question of course, but I don't have time to compile an Android app right now.

Closing this issue, if anyone else continues to have problems please open a new one!

**Comment by breadadams** [comment]
Nice one @mvanroon, will try it out when I can 👍
