### ISSUE TITLE
Add attachment to email

### ISSUE THREAD

**Issue by rishiankush** [includable/react-native-email-link#82]
Is there a way I can add attachments using this module. This module works well as expected but unable to share attachments. I want to share a pdf file. How can I add that?

**Comment by tschoffelen** [comment]
There's currently no way to do that as far as I'm aware. Happy to hear ideas from others though, would be a cool feature to add!

**Comment by rishiankush** [comment]
Thanks @tschoffelen for the confirmation! Highly appreciated

**Comment by MianSaad705** [comment]
Any leads on this feature?
cc: @tschoffelen @rishiankush

**Comment by tschoffelen** [comment]
@MianSaad705 as far as I know this still isn't supported by any of the the major email clients, but if you have a way to implement this, I'd be happy to accept a PR of course!

**Comment by Phoenix1355** [comment]
@tschoffelen It has been possible for quite some time. We've been using the package `react-native-mail` for many years, which has been supporting attachments, but seems to have been abandoned, which I why I'm now hoping that this package could be a replacement 😊
